import type { CategoryId, Question } from './types';

function q(
  category: CategoryId,
  id: string,
  text: string,
  minBid = 1,
  timeLimit = 30,
): Question {
  return {
    id: `q-${category}-${id}`,
    text,
    category,
    timeLimit,
    type: 'count',
    minBid,
  };
}

const questionBank: Question[] = [
  q('allgemeinwissen', 'automarken', 'Wie viele Automarken kann dein Buddy nennen?', 3),
  q('allgemeinwissen', 'superhelden', 'Wie viele Superhelden kann dein Buddy nennen?', 3),
  q(
    'allgemeinwissen',
    'schauspieler',
    'Wie viele Schauspielerinnen oder Schauspieler kann dein Buddy nennen?',
    3,
  ),
  q(
    'allgemeinwissen',
    'filme-zahl',
    'Wie viele Filme mit einer Zahl im Titel kann dein Buddy nennen?',
    2,
  ),
  q('allgemeinwissen', 'streamingdienste', 'Wie viele Streamingdienste kann dein Buddy nennen?', 2),
  q(
    'allgemeinwissen',
    'social-media-plattformen',
    'Wie viele Social-Media-Plattformen kann dein Buddy nennen?',
    3,
  ),
  q('allgemeinwissen', 'smartphone-marken', 'Wie viele Smartphone-Marken kann dein Buddy nennen?', 2),
  q(
    'allgemeinwissen',
    'videospielkonsolen',
    'Wie viele Videospielkonsolen kann dein Buddy nennen?',
    2,
  ),
  q('allgemeinwissen', 'pokemon', 'Wie viele Pokémon kann dein Buddy nennen?', 5),
  q('allgemeinwissen', 'disney-figuren', 'Wie viele Disney-Figuren kann dein Buddy nennen?', 4),
  q(
    'allgemeinwissen',
    'harry-potter-charaktere',
    'Wie viele Harry-Potter-Charaktere kann dein Buddy nennen?',
    3,
  ),
  q(
    'allgemeinwissen',
    'harry-potter-zaubersprueche',
    'Wie viele Harry-Potter-Zaubersprüche kann dein Buddy nennen?',
    2,
  ),
  q(
    'allgemeinwissen',
    'star-wars-charaktere',
    'Wie viele Star-Wars-Charaktere kann dein Buddy nennen?',
    3,
  ),
  q('allgemeinwissen', 'musikinstrumente', 'Wie viele Musikinstrumente kann dein Buddy nennen?', 4),
  q('allgemeinwissen', 'musikgenres', 'Wie viele Musikgenres kann dein Buddy nennen?', 3),
  q('allgemeinwissen', 'bands', 'Wie viele Bands kann dein Buddy nennen?', 4),
  q(
    'allgemeinwissen',
    'solo-musiker',
    'Wie viele Solo-Musikerinnen oder Solo-Musiker kann dein Buddy nennen?',
    3,
  ),
  q('allgemeinwissen', 'sportarten', 'Wie viele Sportarten kann dein Buddy nennen?', 4),
  q(
    'allgemeinwissen',
    'olympische-sportarten',
    'Wie viele olympische Sportarten kann dein Buddy nennen?',
    3,
  ),
  q(
    'allgemeinwissen',
    'fussballvereine-deutschland',
    'Wie viele Fußballvereine aus Deutschland kann dein Buddy nennen?',
    4,
  ),
  q(
    'allgemeinwissen',
    'fussballvereine-europa',
    'Wie viele Fußballvereine aus Europa kann dein Buddy nennen?',
    4,
  ),
  q('allgemeinwissen', 'berufe', 'Wie viele Berufe kann dein Buddy nennen?', 5),
  q('allgemeinwissen', 'schulfaecher', 'Wie viele Schulfächer kann dein Buddy nennen?', 3),
  q('allgemeinwissen', 'sprachen', 'Wie viele Sprachen kann dein Buddy nennen?', 4),
  q('allgemeinwissen', 'haustierarten', 'Wie viele Haustierarten kann dein Buddy nennen?', 2),
  q('allgemeinwissen', 'hunderassen', 'Wie viele Hunderassen kann dein Buddy nennen?', 3),
  q('allgemeinwissen', 'dinosaurierarten', 'Wie viele Dinosaurierarten kann dein Buddy nennen?', 2),
  q(
    'allgemeinwissen',
    'planeten-zwergplaneten',
    'Wie viele Planeten oder Zwergplaneten kann dein Buddy nennen?',
    3,
  ),
  q('allgemeinwissen', 'sternzeichen', 'Wie viele Sternzeichen kann dein Buddy nennen?', 3),
  q('allgemeinwissen', 'chemische-elemente', 'Wie viele chemische Elemente kann dein Buddy nennen?', 3),
  q('allgemeinwissen', 'erfindungen', 'Wie viele bekannte Erfindungen kann dein Buddy nennen?', 3),
  q('allgemeinwissen', 'brettspiele', 'Wie viele Brettspiele kann dein Buddy nennen?', 3),
  q('allgemeinwissen', 'kartenspiele', 'Wie viele Kartenspiele kann dein Buddy nennen?', 2),
  q('allgemeinwissen', 'kleidungsmarken', 'Wie viele Kleidungsmarken kann dein Buddy nennen?', 3),
  q(
    'allgemeinwissen',
    'nobelpreistraeger',
    'Wie viele Nobelpreisträgerinnen oder Nobelpreisträger kann dein Buddy nennen?',
    1,
  ),
  q('allgemeinwissen', 'betriebssysteme', 'Wie viele Betriebssysteme kann dein Buddy nennen?', 2),
  q('allgemeinwissen', 'programmiersprachen', 'Wie viele Programmiersprachen kann dein Buddy nennen?', 2),
  q('allgemeinwissen', 'dateiendungen', 'Wie viele Dateiendungen kann dein Buddy nennen?', 4),
  q('allgemeinwissen', 'waehrungen', 'Wie viele Währungen kann dein Buddy nennen?', 3),
  q('allgemeinwissen', 'masseinheiten', 'Wie viele Maßeinheiten kann dein Buddy nennen?', 4),
  q(
    'allgemeinwissen',
    'griechisches-alphabet',
    'Wie viele Buchstaben des griechischen Alphabets kann dein Buddy nennen?',
    2,
  ),
  q('allgemeinwissen', 'sternbilder', 'Wie viele Sternbilder kann dein Buddy nennen?', 2),
  q('allgemeinwissen', 'suchmaschinen', 'Wie viele Suchmaschinen kann dein Buddy nennen?', 2),
  q(
    'allgemeinwissen',
    'videospiel-franchises',
    'Wie viele Videospiel-Franchises kann dein Buddy nennen?',
    3,
  ),
  q('allgemeinwissen', 'comicfiguren', 'Wie viele Comicfiguren kann dein Buddy nennen?', 4),
  q(
    'allgemeinwissen',
    'milliardaere',
    'Wie viele bekannte Milliardärinnen oder Milliardäre kann dein Buddy nennen?',
    2,
  ),
  q('allgemeinwissen', 'taenze', 'Wie viele Tänze kann dein Buddy nennen?', 3),

  q('geographie', 'laender', 'Wie viele Länder kann dein Buddy nennen?', 5),
  q('geographie', 'laender-europa', 'Wie viele Länder in Europa kann dein Buddy nennen?', 4),
  q('geographie', 'laender-ausserhalb-europas', 'Wie viele Länder außerhalb Europas kann dein Buddy nennen?', 4),
  q('geographie', 'laender-a', 'Wie viele Länder mit dem Anfangsbuchstaben A kann dein Buddy nennen?', 2),
  q('geographie', 'hauptstaedte', 'Wie viele Hauptstädte kann dein Buddy nennen?', 4),
  q('geographie', 'hauptstaedte-europa', 'Wie viele europäische Hauptstädte kann dein Buddy nennen?', 3),
  q('geographie', 'bundeslaender', 'Wie viele deutsche Bundesländer kann dein Buddy nennen?', 3),
  q(
    'geographie',
    'landeshauptstaedte-bundeslaender',
    'Wie viele Landeshauptstädte deutscher Bundesländer kann dein Buddy nennen?',
    3,
  ),
  q('geographie', 'staedte-deutschland', 'Wie viele Städte in Deutschland kann dein Buddy nennen?', 5),
  q('geographie', 'staedte-europa', 'Wie viele Städte in Europa kann dein Buddy nennen?', 5),
  q('geographie', 'staedte-usa', 'Wie viele Städte in den USA kann dein Buddy nennen?', 3),
  q('geographie', 'us-bundesstaaten', 'Wie viele US-Bundesstaaten kann dein Buddy nennen?', 3),
  q('geographie', 'meere-ozeane', 'Wie viele Meere oder Ozeane kann dein Buddy nennen?', 3),
  q('geographie', 'fluesse', 'Wie viele Flüsse kann dein Buddy nennen?', 3),
  q('geographie', 'fluesse-deutschland', 'Wie viele Flüsse in Deutschland kann dein Buddy nennen?', 3),
  q('geographie', 'berge-gebirge', 'Wie viele Berge oder Gebirge kann dein Buddy nennen?', 3),
  q('geographie', 'inseln', 'Wie viele Inseln kann dein Buddy nennen?', 3),
  q('geographie', 'wuesten', 'Wie viele Wüsten kann dein Buddy nennen?', 2),
  q('geographie', 'seen', 'Wie viele Seen kann dein Buddy nennen?', 3),
  q('geographie', 'laender-afrika', 'Wie viele Länder in Afrika kann dein Buddy nennen?', 4),
  q('geographie', 'laender-asien', 'Wie viele Länder in Asien kann dein Buddy nennen?', 4),
  q('geographie', 'laender-suedamerika', 'Wie viele Länder in Südamerika kann dein Buddy nennen?', 3),
  q('geographie', 'flagge-rot', 'Wie viele Länder mit einer Flagge mit Rot kann dein Buddy nennen?', 4),
  q(
    'geographie',
    'bauwerke-wahrzeichen',
    'Wie viele bekannte Bauwerke oder Wahrzeichen kann dein Buddy nennen?',
    3,
  ),
  q(
    'geographie',
    'autokennzeichen-orte',
    'Wie viele deutsche Autokennzeichen-Kürzel mit zugehörigem Ort kann dein Buddy nennen?',
    2,
  ),
  q('geographie', 'flughaefen', 'Wie viele Flughäfen kann dein Buddy nennen?', 3),
  q(
    'geographie',
    'weltwunder',
    'Wie viele Weltwunder der Antike oder der Neuzeit kann dein Buddy nennen?',
    2,
  ),
  q('geographie', 'vulkane', 'Wie viele Vulkane kann dein Buddy nennen?', 2),
  q('geographie', 'stadtstaaten', 'Wie viele Stadtstaaten kann dein Buddy nennen?', 2),
  q('geographie', 'euro-laender', 'Wie viele Länder mit dem Euro als Währung kann dein Buddy nennen?', 3),
  q(
    'geographie',
    'hauptstaedte-b',
    'Wie viele Hauptstädte mit dem Anfangsbuchstaben B kann dein Buddy nennen?',
    2,
  ),

  q('kreativ', 'blaue-dinge', 'Wie viele blaue Dinge kann dein Buddy nennen?', 4),
  q('kreativ', 'runde-dinge', 'Wie viele runde Dinge kann dein Buddy nennen?', 4),
  q('kreativ', 'strom-dinge', 'Wie viele Dinge, die Strom brauchen, kann dein Buddy nennen?', 4),
  q('kreativ', 'woerter-m', 'Wie viele Wörter mit dem Anfangsbuchstaben M kann dein Buddy nennen?', 5),
  q('kreativ', 'reimwoerter-stein', 'Wie viele Reimwörter auf „Stein“ kann dein Buddy nennen?', 3),
  q('kreativ', 'reimwoerter-licht', 'Wie viele Reimwörter auf „Licht“ kann dein Buddy nennen?', 3),
  q('kreativ', 'reimwoerter-zeit', 'Wie viele Reimwörter auf „Zeit“ kann dein Buddy nennen?', 3),
  q('kreativ', 'reimwoerter-haus', 'Wie viele Reimwörter auf „Haus“ kann dein Buddy nennen?', 3),
  q('kreativ', 'tiergeraeusche', 'Wie viele Tiergeräusche kann dein Buddy vormachen?', 3),
  q(
    'kreativ',
    'zeichnen-kategorie',
    'Wie viele Begriffe aus einer gezogenen Kategorie kann dein Buddy in 1 Minute so zeichnen, dass sein Team sie errät?',
    2,
    60,
  ),
  q('kreativ', 'logos-zeichnen', 'Wie viele bekannte Logos kann dein Buddy zeichnen?', 2),
  q(
    'kreativ',
    'alphabet-rueckwaerts',
    'Wie viele Buchstaben kann dein Buddy rückwärts im Alphabet nennen?',
    5,
  ),
  q('kreativ', 'woerter-sch', 'Wie viele Wörter kann dein Buddy nennen, die mit „Sch“ anfangen?', 4),
  q(
    'kreativ',
    'woerter-fuenf-buchstaben',
    'Wie viele Wörter mit genau fünf Buchstaben kann dein Buddy nennen?',
    5,
  ),
  q('kreativ', 'doppelbuchstaben', 'Wie viele Wörter mit Doppelbuchstaben kann dein Buddy nennen?', 4),
  q('kreativ', 'woerter-ver', 'Wie viele Wörter, die mit „Ver-“ anfangen, kann dein Buddy nennen?', 4),
  q('kreativ', 'endung-ung', 'Wie viele Wörter mit der Endung „-ung“ kann dein Buddy nennen?', 4),
  q('kreativ', 'woerter-b', 'Wie viele Wörter mit dem Anfangsbuchstaben B kann dein Buddy nennen?', 5),

  q('koerperlich', 'kniebeugen', 'Wie viele Kniebeugen schafft dein Buddy in 30 Sekunden?', 5),
  q('koerperlich', 'hampelmaenner', 'Wie viele Hampelmänner schafft dein Buddy in 30 Sekunden?', 5),
  q('koerperlich', 'liegestuetze', 'Wie viele Liegestütze schafft dein Buddy in 30 Sekunden?', 2),
  q('koerperlich', 'wand-sitzposition', 'Wie viele Sekunden kann dein Buddy die Wand-Sitzposition halten?', 10, 60),
  q(
    'koerperlich',
    'buch-balancieren',
    'Wie viele Sekunden kann dein Buddy ein Buch auf dem Kopf balancieren und dabei langsam im Kreis gehen?',
    5,
    60,
  ),
  q(
    'koerperlich',
    'loeffel-nase',
    'Wie viele Sekunden kann dein Buddy einen Löffel auf der Nase balancieren?',
    5,
    60,
  ),
  q(
    'koerperlich',
    'wurfgegenstand-korb',
    'Wie oft trifft dein Buddy nacheinander mit einem weichen Wurfgegenstand in einen improvisierten Korb?',
    1,
    60,
  ),
  q(
    'koerperlich',
    'wasserflasche-arm',
    'Wie viele Sekunden kann dein Buddy eine volle Wasserflasche mit ausgestrecktem Arm halten?',
    5,
    60,
  ),
  q(
    'koerperlich',
    'ein-bein-augen-zu',
    'Wie viele Sekunden kann dein Buddy auf einem Bein stehen und dabei die Augen schließen?',
    5,
    60,
  ),
  q('koerperlich', 'unterarmstuetz', 'Wie viele Sekunden kann dein Buddy einen Unterarmstütz halten?', 10, 60),
  q(
    'koerperlich',
    'superman-hold',
    'Wie viele Sekunden kann dein Buddy einen Superman-Hold auf dem Bauch halten?',
    5,
    60,
  ),
  q(
    'koerperlich',
    'muenzturm',
    'Wie viele Münzen kann dein Buddy mit einer Hand zu einem Turm stapeln?',
    3,
  ),
  q(
    'koerperlich',
    'luftballon-atem',
    'Wie viele Sekunden kann dein Buddy einen Luftballon nur mit dem Atem in der Luft halten?',
    5,
    60,
  ),

  q('essen-trinken', 'gewuerze', 'Wie viele Gewürze kann dein Buddy nennen?', 4),
  q('essen-trinken', 'obstsorten', 'Wie viele Obstsorten kann dein Buddy nennen?', 4),
  q('essen-trinken', 'gemuesesorten', 'Wie viele Gemüsesorten kann dein Buddy nennen?', 4),
  q(
    'essen-trinken',
    'lebensmittel-a',
    'Wie viele Lebensmittel mit dem Anfangsbuchstaben A kann dein Buddy nennen?',
    3,
  ),
  q('essen-trinken', 'suessigkeiten', 'Wie viele Süßigkeiten kann dein Buddy nennen?', 4),
  q('essen-trinken', 'nudelsorten', 'Wie viele Nudelsorten kann dein Buddy nennen?', 3),
  q('essen-trinken', 'kaesesorten', 'Wie viele Käsesorten kann dein Buddy nennen?', 3),
  q('essen-trinken', 'brotsorten', 'Wie viele Brotsorten kann dein Buddy nennen?', 3),
  q('essen-trinken', 'cocktails-longdrinks', 'Wie viele Cocktails oder Longdrinks kann dein Buddy nennen?', 3),
  q('essen-trinken', 'biersorten', 'Wie viele Biersorten kann dein Buddy nennen?', 2),
  q('essen-trinken', 'biermarken', 'Wie viele Biermarken kann dein Buddy nennen?', 3),
  q('essen-trinken', 'kaffeespezialitaeten', 'Wie viele Kaffeespezialitäten kann dein Buddy nennen?', 2),
  q('essen-trinken', 'teesorten', 'Wie viele Teesorten kann dein Buddy nennen?', 3),
  q('essen-trinken', 'fast-food-ketten', 'Wie viele Fast-Food-Ketten kann dein Buddy nennen?', 2),
  q('essen-trinken', 'rote-lebensmittel', 'Wie viele rote Lebensmittel kann dein Buddy nennen?', 4),
  q('essen-trinken', 'kuechenutensilien', 'Wie viele Küchenutensilien kann dein Buddy nennen?', 4),
  q('essen-trinken', 'supermarktketten', 'Wie viele Supermarktketten kann dein Buddy nennen?', 3),
  q('essen-trinken', 'nusssorten', 'Wie viele Nusssorten kann dein Buddy nennen?', 2),
  q('essen-trinken', 'tiefkuehlpizzamarken', 'Wie viele Tiefkühlpizzamarken kann dein Buddy nennen?', 2),
  q('essen-trinken', 'softdrinkmarken', 'Wie viele Softdrinkmarken kann dein Buddy nennen?', 3),
  q('essen-trinken', 'mineralwassermarken', 'Wie viele Mineralwassermarken kann dein Buddy nennen?', 2),
  q('essen-trinken', 'pilzarten', 'Wie viele Pilzarten kann dein Buddy nennen?', 2),
  q('essen-trinken', 'kraeuter', 'Wie viele Kräuter kann dein Buddy nennen?', 3),

  q('geschichte', 'griechische-goetter', 'Wie viele griechische Göttinnen oder Götter kann dein Buddy nennen?', 3),
  q(
    'geschichte',
    'griechische-philosophen',
    'Wie viele griechische Philosophinnen oder Philosophen kann dein Buddy nennen?',
    2,
  ),
  q(
    'geschichte',
    'historische-herrschende',
    'Wie viele historische Herrscherinnen oder Herrscher kann dein Buddy nennen?',
    2,
  ),
  q(
    'geschichte',
    'entdeckende',
    'Wie viele berühmte Entdeckerinnen oder Entdecker kann dein Buddy nennen?',
    2,
  ),
  q('geschichte', 'epochen', 'Wie viele historische Epochen kann dein Buddy nennen?', 2),
  q('geschichte', 'antike-kulturen', 'Wie viele antike Kulturen kann dein Buddy nennen?', 2),
  q('geschichte', 'schlachten', 'Wie viele bekannte Schlachten kann dein Buddy nennen?', 1),
  q('geschichte', 'kriege', 'Wie viele Kriege kann dein Buddy nennen?', 2),
  q(
    'geschichte',
    'bundeskanzler',
    'Wie viele deutsche Bundeskanzlerinnen oder Bundeskanzler kann dein Buddy nennen?',
    2,
  ),
  q('geschichte', 'us-praesidenten', 'Wie viele US-Präsidenten kann dein Buddy nennen?', 2),
  q(
    'geschichte',
    'wissenschaft-erfindung',
    'Wie viele berühmte Personen aus Wissenschaft oder Erfindung kann dein Buddy nennen?',
    2,
  ),
  q('geschichte', 'malende', 'Wie viele berühmte Malerinnen oder Maler kann dein Buddy nennen?', 2),
  q('geschichte', 'komponierende', 'Wie viele Komponistinnen oder Komponisten kann dein Buddy nennen?', 2),
  q('geschichte', 'buecher', 'Wie viele berühmte Bücher kann dein Buddy nennen?', 3),
  q('geschichte', 'autoren', 'Wie viele Autorinnen oder Autoren kann dein Buddy nennen?', 3),
  q('geschichte', 'deutsche-dichtende', 'Wie viele deutsche Dichterinnen oder Dichter kann dein Buddy nennen?', 2),
  q('geschichte', 'shakespeare-stuecke', 'Wie viele Shakespeare-Stücke kann dein Buddy nennen?', 1),
  q('geschichte', 'grimm-maerchen', 'Wie viele Märchen der Brüder Grimm kann dein Buddy nennen?', 3),
  q('geschichte', 'religionen', 'Wie viele Religionen kann dein Buddy nennen?', 3),
  q('geschichte', 'feiertage-deutschland', 'Wie viele Feiertage in Deutschland kann dein Buddy nennen?', 3),
  q('geschichte', 'koeniginnen-koenige', 'Wie viele bekannte Königinnen oder Könige kann dein Buddy nennen?', 2),
  q('geschichte', 'pharaonen', 'Wie viele Pharaoninnen oder Pharaonen kann dein Buddy nennen?', 1),
  q('geschichte', 'personen-altes-rom', 'Wie viele bekannte Personen aus dem Alten Rom kann dein Buddy nennen?', 2),
  q('geschichte', 'historische-erfindungen', 'Wie viele historische Erfindungen kann dein Buddy nennen?', 2),
  q('geschichte', 'burgen-schloesser', 'Wie viele bekannte Burgen oder Schlösser kann dein Buddy nennen?', 2),
];

export function getQuestionBank(): Question[] {
  return questionBank.map((question) => ({ ...question }));
}

export function filterQuestionsByCategories(
  questions: Question[],
  selectedCategories: CategoryId[],
): Question[] {
  const selectedCategorySet = new Set(selectedCategories);

  return questions
    .filter((question) => selectedCategorySet.has(question.category))
    .map((question) => ({ ...question }));
}

export function createQuestionDeck(random = Math.random): Question[] {
  const questions = getQuestionBank();

  for (let index = questions.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(random() * (index + 1));
    const question = questions[index];

    questions[index] = questions[swapIndex];
    questions[swapIndex] = question;
  }

  return questions;
}
